export const styleChatScreen = {
  container: {flex: 1},
  containerHeader: {
    backgroundColor: '#7c77cd',
    justifyContent: 'center',
    alignItems: 'center',
  },
  flUser: {marginVertical: 5},
  ctnNameUser: {
    borderBottomWidth: 0.1,
    borderBottomColor: 'gray',
    height: '8%',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
    elevation: 1,
  },
  txtName: {color: '#7c77cd', fontSize: 20},
  ctnFooter: {
    width: '100%',
    borderTopColor: 'gray',
    borderTopWidth: 0.3,
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  iconPlus: {marginTop: 5, fontSize: 40, color: '#7c77cd'},
  input: {
    borderWidth: 0.3,
    borderColor: 'gray',
    width: '60%',
    height: 40,
    marginTop: 5,
    borderRadius: 5,
  },
  send: {color: '#7c77cd', fontSize: 20, marginTop: 10},
  image: {
    width: 40,
    height: 40,
    borderRadius: 40 / 2,
  },
  ctnRender: {
    marginTop: 10,
    marginHorizontal: 15,
    flexDirection: 'row',
  },
  ctnAvt: {paddingRight: 7},
  imageRender: {
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
  },
  textRender: {
    borderRadius: 5,
    padding: 10,
    fontSize: 20,
  },
};
